### ISSUE TITLE
Nav content not saved per site

### ISSUE THREAD

**Issue by truszko1** [verbb/cp-nav#118]
### Describe the bug

We have two sites enabled, and we have enabled the navigation for both sites in the settings for each handle.

Nav for site 1: /admin/navigation/navs/build/2/default
Nav for site 2: /admin/navigation/navs/build/2/secondarySite

Issue: changing the content of the navigation for one site changes the content for the other site, too.

While there is a toggle to switch between sites on a specific navigation content build page, the content doesn't remain unique for different sites.

### Steps to reproduce

1. Install plugin
2. Create a secondary site for multi-site
3. Create a navigation
4. Enable both sites for the navigation
5. Notice that changing the content of the navigation for one site changes the content for the other site, too.

### Craft CMS version

3.7.55.2

### Plugin version

3.0.17

### Multi-site?

Yes

### Additional context

Happens 100% of the time in dev and beyond. I tried reinstalling the plugin and starting fresh.

**Comment by engram-design** [comment]
Did you mean to post this on https://github.com/verbb/navigation?

**Comment by truszko1** [comment]
Oops. I got plugins confused. Sorry!
