### ISSUE TITLE
Add 'groups' or titles to segment links

### ISSUE THREAD

**Issue by masugadesign** [verbb/cp-nav#25]
Your plugin looks great. Does it allow for grouping or segmenting groups of links like Craft Sidebar Enhancer? https://github.com/picdorsey/craft-sidebarenhancer or would that be part of "Support for sub-navigation" that is in your Roadmap?

**Comment by engram-design** [comment]
Thats correct, looking to include this sort of functionality soon, so much more of a menu-builder.

**Comment by svenjungnickel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add 'groups' or titles to segment links](https://trello.com/c/kc9KuPn2/18-add-groups-or-titles-to-segment-links)

**Comment by svenjungnickel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add 'groups' or titles to segment links](https://trello.com/c/kc9KuPn2/18-add-groups-or-titles-to-segment-links)

**Comment by KatieMFritz** [comment]
Ooh, this would be awesome! Just being able to add an item without a link would work for this.

**Comment by KatieMFritz** [comment]
Hey @engram-design, I know this is a free plugin. How much would you want to be paid to add menu builder support (nested menu items) or at least section labels to this? I'd be interested! 😁

**Comment by engram-design** [comment]
@KatieMFritz The way I would want to tackle this is a major change in how the plugin works, similar to how [Navigation](https://plugins.craftcms.com/navigation) works. Its on my todo list for sure, but its a reasonable amount of work for a free plugin. 

We're also not taking paid work at the moment, but I know you're keen about this so I'll see what we can do.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0).

Nested menu items will come much later (there's a great deal more things to consider here - but maybe one day!). Feel free to make another ticket for this specifically.

**Comment by KatieMFritz** [comment]
Awesome! Here's the feature request, but I'm very happy with this improvement for now.
https://github.com/verbb/cp-nav/issues/64
