### ISSUE TITLE
Override the selected item class

### ISSUE THREAD

**Issue by simplethemes** [verbb/cp-nav#27]
It'd be nice to have the ability to override the selected item (`a.sel`) when a custom menu is active.

For example, if you create a link to that goes to Settings > Fields, the "Settings" tab is always active instead of the "Fields" link. I don't know if this is possible but just thought I'd add a feature request.

**Comment by svenjungnickel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Override the selected item class](https://trello.com/c/i24VGpwc/17-override-the-selected-item-class)

**Comment by engram-design** [comment]
Unfortunately, we don't have control over the selected nav item, as that's automatically figured out by Craft. You could potentially achieve this with JS.

Will ponder some more...

**Comment by mattbloomfield** [comment]
@simplethemes this will do what you're looking for - I use it on our site. 

Unfortunately there is a bit of delay but I'm not sure you could do better without getting into the PHP. I have this running from a custom module. 

```javascript
const verifySelectedNavState = () => {
  const loc = window.location.pathname;
  const regexp = new RegExp(`${loc}$`, "gi");
  const sidebartabs = document.querySelectorAll("#nav > ul > li > a");
  let match = null;
  sidebartabs.forEach((tab) => {
    if (tab.classList.contains("sel") && !match) {
      match = tab;
    }
    tab.classList.remove("sel");
    if (regexp.test(tab.href)) {
      match = tab;
      match.classList.add("sel");
    }
  });
};
```

**Comment by engram-design** [comment]
As of [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) we now have total control over the output of the navigation items, so you should be able to target the selected state a bit better now.
