### ISSUE TITLE
Error when defaultSearchTermOptions are configured

### ISSUE THREAD

**Issue by juresrpcic** [verbb/cp-nav#30]
### Description

I installed the latest version (2.0.1) successfully - no more issues with composer requiring `dev-craft-3` like yesterday. When I tried installing the plugin, I got an error:
```php
PHP Notice – yii\base\ErrorException
Array to string conversion
vendor\verbb\cp-nav\src\models\Navigation.php
(error on line 158) $url = str_replace('{' . $key . '}', $value, $url);
```

I can go back and the plugin appears installed, but it's not functional - the settings page only shows the layouts dropdown and no switches.

After some research, I discovered that a Craft config setting is causing this - in `general.php`, I have this setting under `'*'`:
```php
'defaultSearchTermOptions' => [
	'subLeft' => true,
	'subRight' => true,
],
```

If I disable that part of the config, the plugin works again and doesn't cause the issue on install.

### Steps to reproduce

1. Install plugin - `composer require verbb/cp-nav`
2. Install plugin through CP, get error

### Additional info

- Plugin version: 2.0.1
- Craft version: 3.0.0-RC1

**Comment by juresrpcic** [comment]
It seems any array used in `general.php` causes this issue - the same happens if I have this under the `'dev'` key:
```php
'environmentVariables' => [
	'baseUrl' => 'http://test-website.local/',
	'basePath' => 'C:\web\test-website\public\\',
],
```

**Comment by svenjungnickel** [comment]
Hey @juresrpcic. Thanks for sending that issue. I will look into that and keep you posted.

**Comment by svenjungnickel** [comment]
@juresrpcic the concept of environment variables don't exists anymore in craft 3.
 See [](https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#environment-variables). Hence the array for `environmentVariables` is superfluous. But that doesn't mean there can't be other config variables defined as an array. They're just ignored by CP Nav.

I uploaded a fix to the latest [craft-3](https://github.com/verbb/cp-nav/tree/craft-3) branch. Can you install and test it please? To install the latest dev version you have to set the `dev-craft-3` branch (again): `composer require verbb/cp-nav:dev-craft-3`.

**Comment by svenjungnickel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error when defaultSearchTermOptions are configured](https://trello.com/c/w4lT1Odz/16-error-when-defaultsearchtermoptions-are-configured)

**Comment by juresrpcic** [comment]
@svenjungnickel Thanks for the update! I tested this again (with an array for search options in `general.php`) and it's no longer reporting any error (using dev-craft-3 branch).

Re `environmentVariables` - I am aware this is not a thing anymore in Craft 3 - I just wanted to test with another array in `general.php` and had that lying around...

**Comment by svenjungnickel** [comment]
@juresrpcic thanks you tested that. I just tagged a new release. You should be able to install the plugin without adding the dev branch now.
